# Generated by Django 6.0.4 on 2026-05-12 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionOnem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomDomaine', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, unique=True)),
                ('duree', models.IntegerField(help_text='Durée en jours')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congé',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='TypeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Type de décision',
                'verbose_name_plural': 'Types de décision',
            },
        ),
        migrations.CreateModel(
            name='TypeEtatOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Type d'état d'offre",
                'verbose_name_plural': "Types d'états d'offre",
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=13)),
                ('nationalite', models.CharField(default='Congolaise', max_length=50)),
                ('lieuNaissance', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('numeroTelephone', models.CharField(max_length=30)),
                ('quartier', models.CharField(max_length=50)),
                ('avenue', models.CharField(blank=True, max_length=50, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retenu', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('contrat_signe', models.BooleanField(default=False)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='Appl.candidat')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('candidature_acceptee', 'Candidature acceptée'), ('candidature_refusee', 'Candidature refusée'), ('test_programme', 'Test programmé'), ('rappel_test', 'Rappel de test'), ('info_generale', 'Information générale')], max_length=50)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lien', models.CharField(blank=True, max_length=200, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Appl.candidat')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OffreEmploie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('OffreFichier', models.FileField(upload_to='offres_emploi/%Y/%m/%d/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='Appl.domaine')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cvs/%Y/%m/%d/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='Appl.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='Appl.offreemploie')),
            ],
        ),
        migrations.CreateModel(
            name='Onem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appl.decisiononem')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='Appl.offreemploie')),
            ],
            options={
                'verbose_name': 'Traitement ONEM',
                'verbose_name_plural': 'Traitements ONEM',
                'ordering': ['-date_verification'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_test', models.FileField(upload_to='tests/%Y/%m/%d/')),
                ('date_test', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='Appl.offreemploie')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['-date_test'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to='Appl.agent')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='Appl.typeconge')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='Appl.candidature')),
                ('type_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appl.typedecision')),
            ],
            options={
                'verbose_name': 'Décision',
                'verbose_name_plural': 'Décisions',
                'ordering': ['-date_decision'],
            },
        ),
        migrations.CreateModel(
            name='ReglageOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_renouvellement', models.DateField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglage', to='Appl.offreemploie')),
                ('type_etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglages', to='Appl.typeetatoffre')),
            ],
            options={
                'verbose_name': "Réglage d'offre",
                'verbose_name_plural': "Réglages d'offres",
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, null=True)),
                ('note', models.FloatField(help_text='Note en pourcentage (0-100)')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Appl.candidature')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Appl.test')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_evaluation'],
                'unique_together': {('candidature', 'test')},
            },
        ),
    ]
