# Generated by Django 6.0.4 on 2026-05-13 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseDemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('en_attente', 'En attente')], default='en_attente', max_length=50)),
                ('motif_analyse', models.TextField(blank=True, null=True)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('analyste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='Appl.agent')),
                ('demande_conge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='Appl.demandeconge')),
            ],
            options={
                'verbose_name': 'Analyse demande de congé',
                'verbose_name_plural': 'Analyses demandes de congé',
                'ordering': ['-date_analyse'],
            },
        ),
    ]
