# Generated by Django 6.0.4 on 2026-05-13 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appl', '0002_analysedemandeconge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_lu', models.DateTimeField(blank=True, null=True)),
                ('statut_expediteur', models.CharField(choices=[('envoye', 'Envoyé'), ('recu', 'Reçu'), ('lu', 'Lu'), ('supprime', 'Supprimé')], default='envoye', max_length=20)),
                ('statut_destinataire', models.CharField(choices=[('envoye', 'Envoyé'), ('recu', 'Reçu'), ('lu', 'Lu'), ('supprime', 'Supprimé')], default='recu', max_length=20)),
                ('est_lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dernier_message', models.DateTimeField(auto_now=True)),
                ('sujet', models.CharField(blank=True, max_length=200, null=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('dernier_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Appl.message')),
            ],
            options={
                'ordering': ['-date_dernier_message'],
            },
        ),
        migrations.CreateModel(
            name='MessagePieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='messages/%Y/%m/%d/')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('taille', models.IntegerField(default=0)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='Appl.message')),
            ],
        ),
    ]
