# Generated by Django 6.0.4 on 2026-05-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appl', '0003_message_conversation_messagepiecejointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='date_suppression_destinataire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='date_suppression_expediteur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='est_modifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagepiecejointe',
            name='type_fichier',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('pdf', 'PDF'), ('autre', 'Autre')], default='document', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='statut_destinataire',
            field=models.CharField(choices=[('envoye', 'Envoyé'), ('recu', 'Reçu'), ('lu', 'Lu'), ('supprime', 'Supprimé'), ('modifie', 'Modifié')], default='recu', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='statut_expediteur',
            field=models.CharField(choices=[('envoye', 'Envoyé'), ('recu', 'Reçu'), ('lu', 'Lu'), ('supprime', 'Supprimé'), ('modifie', 'Modifié')], default='envoye', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
