# Generated by Django 6.0.4 on 2026-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appl', '0004_message_date_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_candidats/%Y/%m/%d/'),
        ),
    ]
