# Generated by Django 6.0.4 on 2026-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appl', '0005_candidat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
