# Generated by Django 6.0.4 on 2026-06-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appl', '0006_agent_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_interview', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('date_decision', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='Appl.candidat')),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='Appl.candidature')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='Appl.offreemploie')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['-date_interview'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(blank=True, choices=[('determine', 'Contrat à durée déterminée (CDD)'), ('indetermine', 'Contrat à durée indéterminée (CDI)')], max_length=20, null=True)),
                ('titre_contrat', models.CharField(default="Contrat d'engagement professionnel", max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_mois', models.IntegerField(blank=True, help_text='Durée en mois pour CDD', null=True)),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire de base mensuel', max_digits=12, null=True)),
                ('prime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avantages', models.TextField(blank=True, help_text='Avantages sociaux (mutuelle, transport, etc.)', null=True)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de signature'), ('accepte', 'Accepté par le candidat'), ('refuse', 'Refusé par le candidat'), ('signe', 'Signé')], default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('date_proposition', models.DateTimeField(auto_now_add=True)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Appl.candidat')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Appl.candidature')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Appl.offreemploie')),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Appl.interview')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_proposition'],
            },
        ),
    ]
