# Generated by Django 6.0.4 on 2026-06-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appl', '0007_interview_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='candidat',
        ),
    ]
