# Generated by Django 6.0.4 on 2026-06-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appl', '0008_remove_interview_candidat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrat',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Contrat', 'verbose_name_plural': 'Contrats'},
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='date_proposition',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='avantages',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='candidature',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='duree_mois',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='prime',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='salaire_base',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='titre_contrat',
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('accepte', 'Accepté par le candidat'), ('refuse', 'Refusé par le candidat'), ('signe', 'Signé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('determine', 'Contrat à durée déterminée (CDD)'), ('indetermine', 'Contrat à durée indéterminée (CDI)')], default='determine', max_length=20),
            preserve_default=False,
        ),
    ]
