# Generated by Django 6.0.4 on 2026-06-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appl', '0009_alter_contrat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='fichier_contrat',
            field=models.FileField(blank=True, null=True, upload_to='contrats/%Y/%m/'),
        ),
    ]
